### ISSUE TITLE
Update Seqviz fork with upstream changes

### ISSUE THREAD

**Issue by drphelps** [AsimovBio/seqviz#9]

**Comment by jpsorensen-asimov** [comment]
Ah did this issue come out of a conversation with @max-asimov? I know he has this PR https://github.com/AsimovBio/kernel-universal/pull/4191 for https://github.com/AsimovBio/kernel-universal/issues/3941 and he and I were chatting briefly about the best way to manage that (to just pick the changes we need, to merge everything as you've specified here, etc).

I know we also have some local changes that aren't in seqviz (yet) - in particular I know I made some type-only changes to conform to some strict null checks. Not sure how much that will complicate things.
